package uk.co.littlehugs.sacramentagenda;

/**
 * Created by hugs on 15/02/16.
 */
public class Acknowledgements {


    private String ACKNOWLEDGEMENT_ID;
    private String ACKNOWLEDGEMENTDATE;
    private String ACKNOWLEDGEMENTPRESIDING;
    private String ACKNOWLEDGEMENTCONDUCTING;
    private String ACKNOWLEDGEMENTSTAKEVISITOR1;
    private String ACKNOWLEDGEMENTSTAKECALLING1;
    private String ACKNOWLEDGEMENTSTAKEVISITOR2;
    private String ACKNOWLEDGEMENTSTAKECALLING2;
    private String ACKNOWLEDGEMENTSTAKEVISITOR3;
    private String ACKNOWLEDGEMENTSTAKECALLING3;
    private String ACKNOWLEDGEMENTUPDATEDATE;
    private String ACKNOWLEDGEMENTSTATUS;

    public Acknowledgements()
    {
        ACKNOWLEDGEMENT_ID = "0";
        ACKNOWLEDGEMENTDATE = "";
        ACKNOWLEDGEMENTPRESIDING = "";
        ACKNOWLEDGEMENTCONDUCTING = "";
        ACKNOWLEDGEMENTSTAKEVISITOR1 = "";
        ACKNOWLEDGEMENTSTAKECALLING1 = "";
        ACKNOWLEDGEMENTSTAKEVISITOR2 = "";
        ACKNOWLEDGEMENTSTAKECALLING2 = "";
        ACKNOWLEDGEMENTSTAKEVISITOR3 = "";
        ACKNOWLEDGEMENTSTAKECALLING3 = "";
        ACKNOWLEDGEMENTUPDATEDATE = "0";
        ACKNOWLEDGEMENTSTATUS = "";
    }

    //for adding
    public Acknowledgements(String aCKNOWLEDGEMENT_ID, String aCKNOWLEDGEMENTDATE, String aCKNOWLEDGEMENTPRESIDING,
                            String aCKNOWLEDGEMENTCONDUCTING, String aCKNOWLEDGEMENTSTAKEVISITOR1, String aCKNOWLEDGEMENTSTAKECALLING1,
                            String aCKNOWLEDGEMENTSTAKEVISITOR2, String aCKNOWLEDGEMENTSTAKECALLING2,
                            String aCKNOWLEDGEMENTSTAKEVISITOR3, String aCKNOWLEDGEMENTSTAKECALLING3, String aCKNOWLEDGEMENTUPDATEDATE,
                            String aCKNOWLEDGEMENTSTATUS) {
        ACKNOWLEDGEMENT_ID = aCKNOWLEDGEMENT_ID;
        ACKNOWLEDGEMENTDATE = aCKNOWLEDGEMENTDATE;
        ACKNOWLEDGEMENTPRESIDING = aCKNOWLEDGEMENTPRESIDING;
        ACKNOWLEDGEMENTCONDUCTING = aCKNOWLEDGEMENTCONDUCTING;
        ACKNOWLEDGEMENTSTAKEVISITOR1 = aCKNOWLEDGEMENTSTAKEVISITOR1;
        ACKNOWLEDGEMENTSTAKECALLING1 = aCKNOWLEDGEMENTSTAKECALLING1;
        ACKNOWLEDGEMENTSTAKEVISITOR2 = aCKNOWLEDGEMENTSTAKEVISITOR2;
        ACKNOWLEDGEMENTSTAKECALLING2 = aCKNOWLEDGEMENTSTAKECALLING2;
        ACKNOWLEDGEMENTSTAKEVISITOR3 = aCKNOWLEDGEMENTSTAKEVISITOR3;
        ACKNOWLEDGEMENTSTAKECALLING3 = aCKNOWLEDGEMENTSTAKECALLING3;
        ACKNOWLEDGEMENTUPDATEDATE = aCKNOWLEDGEMENTUPDATEDATE;
        ACKNOWLEDGEMENTSTATUS =aCKNOWLEDGEMENTSTATUS;
    }

    //for editing
    public Acknowledgements(String aCKNOWLEDGEMENTDATE, String aCKNOWLEDGEMENTPRESIDING,
                         String aCKNOWLEDGEMENTCONDUCTING, String aCKNOWLEDGEMENTSTAKEVISITOR1, String aCKNOWLEDGEMENTSTAKECALLING1,
                            String aCKNOWLEDGEMENTSTAKEVISITOR2, String aCKNOWLEDGEMENTSTAKECALLING2,
                            String aCKNOWLEDGEMENTSTAKEVISITOR3, String aCKNOWLEDGEMENTSTAKECALLING3, String aCKNOWLEDGEMENTUPDATEDATE,
                            String aCKNOWLEDGEMENTSTATUS) {
        ACKNOWLEDGEMENTDATE = aCKNOWLEDGEMENTDATE;
        ACKNOWLEDGEMENTPRESIDING = aCKNOWLEDGEMENTPRESIDING;
        ACKNOWLEDGEMENTCONDUCTING = aCKNOWLEDGEMENTCONDUCTING;
        ACKNOWLEDGEMENTSTAKEVISITOR1 = aCKNOWLEDGEMENTSTAKEVISITOR1;
        ACKNOWLEDGEMENTSTAKECALLING1 = aCKNOWLEDGEMENTSTAKECALLING1;
        ACKNOWLEDGEMENTSTAKEVISITOR2 = aCKNOWLEDGEMENTSTAKEVISITOR2;
        ACKNOWLEDGEMENTSTAKECALLING2 = aCKNOWLEDGEMENTSTAKECALLING2;
        ACKNOWLEDGEMENTSTAKEVISITOR3 = aCKNOWLEDGEMENTSTAKEVISITOR3;
        ACKNOWLEDGEMENTSTAKECALLING3 = aCKNOWLEDGEMENTSTAKECALLING3;
        ACKNOWLEDGEMENTUPDATEDATE = aCKNOWLEDGEMENTUPDATEDATE;
        ACKNOWLEDGEMENTSTATUS = aCKNOWLEDGEMENTSTATUS;
    }

    public String getACKNOWLEDGEMENT_ID()
    {
        return ACKNOWLEDGEMENT_ID;
    }
    public String getACKNOWLEDGEMENTDATE() {return ACKNOWLEDGEMENTDATE; }
    public String getACKNOWLEDGEMENTPRESIDING() {return ACKNOWLEDGEMENTPRESIDING; }
    public String getACKNOWLEDGEMENTCONDUCTING() {return ACKNOWLEDGEMENTCONDUCTING; }
    public String getACKNOWLEDGEMENTSTAKEVISITOR1() {return ACKNOWLEDGEMENTSTAKEVISITOR1; }
    public String getACKNOWLEDGEMENTSTAKECALLING1() {return ACKNOWLEDGEMENTSTAKECALLING1; }
    public String getACKNOWLEDGEMENTSTAKEVISITOR2() {return ACKNOWLEDGEMENTSTAKEVISITOR2; }
    public String getACKNOWLEDGEMENTSTAKECALLING2() {return ACKNOWLEDGEMENTSTAKECALLING2; }
    public String getACKNOWLEDGEMENTSTAKEVISITOR3() {return ACKNOWLEDGEMENTSTAKEVISITOR3; }
    public String getACKNOWLEDGEMENTSTAKECALLING3() {return ACKNOWLEDGEMENTSTAKECALLING3; }
    public String getACKNOWLEDGEMENTUPDATEDATE() {return  ACKNOWLEDGEMENTUPDATEDATE; }
    public String getACKNOWLEDGEMENTSTATUS() {return ACKNOWLEDGEMENTSTATUS; }

    public void setACKNOWEDGEMENT_ID(String id)
    {
        ACKNOWLEDGEMENT_ID=id;
    }
    public void setACKNOWLEDGEMENTDATE(String aCKNOWLEDGEMENTDATE) { ACKNOWLEDGEMENTDATE = aCKNOWLEDGEMENTDATE; }
    public void setACKNOWLEDGEMENTPRESIDING(String aCKNOWLEDGEMENTPRESIDING) { ACKNOWLEDGEMENTPRESIDING = aCKNOWLEDGEMENTPRESIDING; }
    public void setACKNOWLEDGEMENTCONDUCTING(String aCKNOWLEDGEMENTCONDUCTING) { ACKNOWLEDGEMENTCONDUCTING = aCKNOWLEDGEMENTCONDUCTING; }
    public void setACKNOWLEDGEMENTSTAKEVISITOR1(String aCKNOWLEDGEMENTSTAKEVISITOR1) { ACKNOWLEDGEMENTSTAKEVISITOR1 = aCKNOWLEDGEMENTSTAKEVISITOR1; }
    public void setACKNOWLEDGEMENTSTAKECALLING1(String aCKNOWLEDGEMENTSTAKECALLING1) { ACKNOWLEDGEMENTSTAKECALLING1 = aCKNOWLEDGEMENTSTAKECALLING1; }
    public void setACKNOWLEDGEMENTSTAKEVISITOR2(String aCKNOWLEDGEMENTSTAKEVISITOR2) { ACKNOWLEDGEMENTSTAKEVISITOR2 = aCKNOWLEDGEMENTSTAKEVISITOR2; }
    public void setACKNOWLEDGEMENTSTAKECALLING2(String aCKNOWLEDGEMENTSTAKECALLING2) { ACKNOWLEDGEMENTSTAKECALLING2 = aCKNOWLEDGEMENTSTAKECALLING2; }
    public void setACKNOWLEDGEMENTSTAKEVISITOR3(String aCKNOWLEDGEMENTSTAKEVISITOR3) { ACKNOWLEDGEMENTSTAKEVISITOR3 = aCKNOWLEDGEMENTSTAKEVISITOR3; }
    public void setACKNOWLEDGEMENTSTAKECALLING3(String aCKNOWLEDGEMENTSTAKECALLING3) { ACKNOWLEDGEMENTSTAKECALLING3 = aCKNOWLEDGEMENTSTAKECALLING3; }
    public void setACKNOWLEDGEMENTUPDATEDATE(String aCKNOWLEDGEMENTUPDATEDATE) {ACKNOWLEDGEMENTUPDATEDATE = aCKNOWLEDGEMENTUPDATEDATE; }
    public void setACKNOWLEDGEMENTSTATUS(String aCKNOWLEDGEMENTSTATUS) {ACKNOWLEDGEMENTSTATUS = aCKNOWLEDGEMENTSTATUS; }
}