package uk.co.littlehugs.sacramentagenda;

/**
 * Created by hugs on 12/02/16.
 */
public class Agenda {
    private String AGENDA_ID;
    private String AGENDADATE;
    private int AGENDAOPENINGHYMN;
    private String AGENDAOPENINGPRAYER;
    private int AGENDASACRAMENTHYMN;
    private String AGENDAFIRSTSPEAKER;
    private String AGENDASECONDSPEAKER;
    private int AGENDAINTERMEDIATEHYMN;
    private String AGENDAFINALSPEAKER;
    private int AGENDACLOSINGHYMN;
    private String AGENDACLOSINGPRAYER;
    private String AGENDAUPDATEDATE;
    private String AGENDASTATUS;

    public Agenda()
    {
        AGENDA_ID="0";
        AGENDADATE="";
        AGENDAOPENINGHYMN=0;
        AGENDAOPENINGPRAYER="";
        AGENDASACRAMENTHYMN=0;
        AGENDAFIRSTSPEAKER="";
        AGENDASECONDSPEAKER="";
        AGENDAINTERMEDIATEHYMN=0;
        AGENDAFINALSPEAKER="";
        AGENDACLOSINGHYMN=0;
        AGENDACLOSINGPRAYER="";
        AGENDAUPDATEDATE="0";
        AGENDASTATUS="";
    }
    //for adding
    public Agenda(String agendaId, String aGENDADATE,int aGENDAOPENINGHYMN, String aGENDAOPENINGPRAYER, int aGENDASACRAMENTHYMN,
                  String aGENDAFIRSTSPEAKER,String aGENDASECONDSPEAKER,int aGENDAINTERMEDIATEHYMN,String aGENDAFINALSPEAKER,
                  int aGENDACLOSINGHYMN, String aGENDACLOSINGPRAYER, String aGENDAUPDATEDATE, String aGENDASTATUS) {
        AGENDA_ID=agendaId;
        AGENDADATE=aGENDADATE;
        AGENDAOPENINGHYMN=aGENDAOPENINGHYMN;
        AGENDAOPENINGPRAYER=aGENDAOPENINGPRAYER;
        AGENDASACRAMENTHYMN=aGENDASACRAMENTHYMN;
        AGENDAFIRSTSPEAKER=aGENDAFIRSTSPEAKER;
        AGENDASECONDSPEAKER=aGENDASECONDSPEAKER;
        AGENDAINTERMEDIATEHYMN=aGENDAINTERMEDIATEHYMN;
        AGENDAFINALSPEAKER=aGENDAFINALSPEAKER;
        AGENDACLOSINGHYMN=aGENDACLOSINGHYMN;
        AGENDACLOSINGPRAYER=aGENDACLOSINGPRAYER;
        AGENDAUPDATEDATE=aGENDAUPDATEDATE;
        AGENDASTATUS=aGENDASTATUS;
    }

    //for editting
    public Agenda(String aGENDADATE,int aGENDAOPENINGHYMN, String aGENDAOPENINGPRAYER, int aGENDASACRAMENTHYMN,
            String aGENDAFIRSTSPEAKER,String aGENDASECONDSPEAKER,int aGENDAINTERMEDIATEHYMN,String aGENDAFINALSPEAKER,
                          int aGENDACLOSINGHYMN, String aGENDACLOSINGPRAYER, String aGENDAUPDATEDATE, String aGENDASTATUS) {

        AGENDADATE=aGENDADATE;
        AGENDAOPENINGHYMN=aGENDAOPENINGHYMN;
        AGENDAOPENINGPRAYER=aGENDAOPENINGPRAYER;
        AGENDASACRAMENTHYMN=aGENDASACRAMENTHYMN;
        AGENDAFIRSTSPEAKER=aGENDAFIRSTSPEAKER;
        AGENDASECONDSPEAKER=aGENDASECONDSPEAKER;
        AGENDAINTERMEDIATEHYMN=aGENDAINTERMEDIATEHYMN;
        AGENDAFINALSPEAKER=aGENDAFINALSPEAKER;
        AGENDACLOSINGHYMN=aGENDACLOSINGHYMN;
        AGENDACLOSINGPRAYER=aGENDACLOSINGPRAYER;
        AGENDAUPDATEDATE=aGENDAUPDATEDATE;
        AGENDASTATUS=aGENDASTATUS;
    }

    public String getAGENDA_ID()    {   return AGENDA_ID;    }
    public String getAGENDADATE() {return AGENDADATE;    }
    public int getAGENDAOPENINGHYMN() {return AGENDAOPENINGHYMN; }
    public String getAGENDAOPENINGPRAYER() {return AGENDAOPENINGPRAYER; }
    public int getAGENDASACRAMENTHYMN() {return AGENDASACRAMENTHYMN; }
    public String getAGENDAFIRSTSPEAKER() {return AGENDAFIRSTSPEAKER; }
    public String getAGENDASECONDSPEAKER() {return AGENDASECONDSPEAKER; }
    public int getAGENDAINTERMEDIATEHYMN() {return AGENDAINTERMEDIATEHYMN; }
    public String getAGENDAFINALSPEAKER() {return AGENDAFINALSPEAKER; }
    public int getAGENDACLOSINGHYMN() {return AGENDACLOSINGHYMN; }
    public String getAGENDACLOSINGPRAYER() {return AGENDACLOSINGPRAYER; }
    public String getAGENDAUPDATEDATE() {return AGENDAUPDATEDATE; }
    public String getAGENDASTATUS() {return AGENDASTATUS; }

    public void setAGENDA_ID(String id) { AGENDA_ID=id;    }
    public void setAGENDADATE(String aGENDADATE) {
        AGENDADATE = aGENDADATE;
    }
    public void setAGENDAOPENINGHYMN(int aGENDAOPENINGHYMN) { AGENDAOPENINGHYMN = aGENDAOPENINGHYMN; }
    public void setAGENDAOPENINGPRAYER(String aGENDAOPENINGPRAYER) { AGENDAOPENINGPRAYER = aGENDAOPENINGPRAYER; }
    public void setAGENDASACRAMENTHYMN(int aGENDASACRAMENTHYMN) { AGENDASACRAMENTHYMN = aGENDASACRAMENTHYMN; }
    public void setAGENDAFIRSTSPEAKER(String aGENDAFIRSTSPEAKER) { AGENDAFIRSTSPEAKER = aGENDAFIRSTSPEAKER; }
    public void setAGENDASECONDSPEAKER(String aGENDASECONDSPEAKER) { AGENDASECONDSPEAKER = aGENDASECONDSPEAKER; }
    public void setAGENDAINTERMEDIATEHYMN(int aGENDAINTERMEDIATEHYMN) { AGENDAINTERMEDIATEHYMN = aGENDAINTERMEDIATEHYMN; }
    public void setAGENDAFINALSPEAKER(String aGENDAFINALSPEAKER) { AGENDAFINALSPEAKER = aGENDAFINALSPEAKER; }
    public void setAGENDACLOSINGHYMN(int aGENDACLOSINGHYMN) { AGENDACLOSINGHYMN = aGENDACLOSINGHYMN; }
    public void setAGENDACLOSINGPRAYER(String aGENDACLOSINGPRAYER) { AGENDACLOSINGPRAYER = aGENDACLOSINGPRAYER; }
    public void setAGENDAUPDATEDATE(String aGENDAUPDATEDATE) { AGENDAUPDATEDATE = aGENDAUPDATEDATE; }
    public void setAGENDASTATUS(String aGENDASTATUS) {AGENDASTATUS = aGENDASTATUS; }
}







