package uk.co.littlehugs.sacramentagenda;

/**
 * Created by hugs on 12/02/16.
 */
public class Announcements {
    private String ANNOUNCEMENTS_ID;
    private String ANNOUNCEMENTSDATE;
    private String ANNOUNCEMENTS;
    private String ANNOUNCEMENTSUPDATEDATE;
    private String ANNOUNCEMENTSSTATUS;

    public Announcements()
    {
        ANNOUNCEMENTS_ID = "0";
        ANNOUNCEMENTSDATE = "";
        ANNOUNCEMENTS = "";
        ANNOUNCEMENTSUPDATEDATE = "0";
        ANNOUNCEMENTSSTATUS = "";
    }

    //for adding
    public Announcements(String aNNOUNCEMENTS_ID, String aNNOUNCEMENTSDATE, String aNNOUNCEMENTS, String aNNOUNCEMENTSUPDATEDATE, String aNNOUNCEMENTSSTATUS) {
        ANNOUNCEMENTS_ID = aNNOUNCEMENTS_ID;
        ANNOUNCEMENTSDATE = aNNOUNCEMENTSDATE;
        ANNOUNCEMENTS = aNNOUNCEMENTS;
        ANNOUNCEMENTSUPDATEDATE = aNNOUNCEMENTSUPDATEDATE;
        ANNOUNCEMENTSSTATUS = aNNOUNCEMENTSSTATUS;
    }

    //for editing
    public Announcements(String aNNOUNCEMENTSDATE, String aNNOUNCEMENTS, String aNNOUNCEMENTSUPDATEDATE, String aNNOUNCEMENTSSTATUS) {
        ANNOUNCEMENTSDATE = aNNOUNCEMENTSDATE;
        ANNOUNCEMENTS = aNNOUNCEMENTS;
        ANNOUNCEMENTSUPDATEDATE = aNNOUNCEMENTSUPDATEDATE;
        ANNOUNCEMENTSSTATUS = aNNOUNCEMENTSSTATUS;
    }

    public String getANNOUNCEMENTS_ID()
    {
        return ANNOUNCEMENTS_ID;
    }
    public String getANNOUNCEMENTSDATE() {return ANNOUNCEMENTSDATE; }
    public String getANNOUNCEMENTS() {return ANNOUNCEMENTS; }
    public String getANNOUNCEMENTSUPDATEDATE() {return  ANNOUNCEMENTSUPDATEDATE; }
    public String getANNOUNCEMENTSSTATUS() {return  ANNOUNCEMENTSSTATUS; }

    public void setANNOUNCEMENTS_ID(String id) {ANNOUNCEMENTS_ID=id;}
    public void setANNOUNCEMENTSDATE(String aNNOUNCEMENTSDATE) { ANNOUNCEMENTSDATE = aNNOUNCEMENTSDATE; }
    public void setANNOUNCEMENTS(String aNNOUNCEMENTS) { ANNOUNCEMENTS = aNNOUNCEMENTS; }
    public void setANNOUNCEMENTSUPDATEDATE(String aNNOUNCEMENTSUPDATEDATE) {ANNOUNCEMENTSUPDATEDATE = aNNOUNCEMENTSUPDATEDATE;}
    public void setANNOUNCEMENTSSTATUS(String aNNOUCEMENTSSTATUS) {ANNOUNCEMENTSSTATUS = aNNOUCEMENTSSTATUS; }
}