package uk.co.littlehugs.sacramentagenda;

/**
 * Created by hugs on 12/02/16.
 */
public class StakeBusiness {
    private String STAKEBUSINESS_ID;
    private String STAKEBUSINESSDATE;
    private String STAKEBUSINESS;
    private String STAKEBUSINESSUPDATEDATE;
    private String STAKEBUSINESSSTATUS;

    public StakeBusiness()
    {
        STAKEBUSINESS_ID = "0";
        STAKEBUSINESSDATE = "";
        STAKEBUSINESS = "";
        STAKEBUSINESSUPDATEDATE = "0";
        STAKEBUSINESSSTATUS = "";
    }

    //for adding
    public StakeBusiness(String sTAKEBUSINESS_ID, String sTAKEBUSINESSDATE, String sTAKEBUSINESS, String sTAKEBUSINESSUPDATEDATE, String sTAKEBUSINESSSTATUS) {
        STAKEBUSINESS_ID = sTAKEBUSINESS_ID;
        STAKEBUSINESSDATE = sTAKEBUSINESSDATE;
        STAKEBUSINESS = sTAKEBUSINESS;
        STAKEBUSINESSUPDATEDATE = sTAKEBUSINESSUPDATEDATE;
        STAKEBUSINESSSTATUS = sTAKEBUSINESSSTATUS;
    }

    //for editing
    public StakeBusiness(String sTAKEBUSINESSDATE, String sTAKEBUSINESS, String sTAKEBUSINESSUPDATEDATE, String sTAKEBUSINESSSTATUS) {
        //STAKEBUSINESS_ID = sTAKEBUSINESS_ID;
        STAKEBUSINESSDATE = sTAKEBUSINESSDATE;
        STAKEBUSINESS = sTAKEBUSINESS;
        STAKEBUSINESSUPDATEDATE = sTAKEBUSINESSUPDATEDATE;
        STAKEBUSINESSSTATUS = sTAKEBUSINESSSTATUS;
    }

    public String getSTAKEBUSINESS_ID() {return STAKEBUSINESS_ID;}
    public String getSTAKEBUSINESSDATE() {return STAKEBUSINESSDATE; }
    public String getSTAKEBUSINESS() {return STAKEBUSINESS; }
    public String getSTAKEBUSINESSUPDATEDATE() {return  STAKEBUSINESSUPDATEDATE; }
    public String getSTAKEBUSINESSSTATUS() {return  STAKEBUSINESSSTATUS;}

    public void setSTAKEBUSINESS_ID(String id) {STAKEBUSINESS_ID=id;}
    public void setSTAKEBUSINESSDATE(String sTAKEBUSINESSDATE) { STAKEBUSINESSDATE = sTAKEBUSINESSDATE; }
    public void setSTAKEBUSINESS(String sTAKEBUSINESS) { STAKEBUSINESS = sTAKEBUSINESS; }
    public void setSTAKEBUSINESSUPDATEDATE(String sTAKEBUSINESSUPDATEDATE) { STAKEBUSINESSUPDATEDATE = sTAKEBUSINESSUPDATEDATE; }
    public void setSTAKEBUSINESSSTATUS(String sTAKEBUSINESSSTATUS) { STAKEBUSINESSSTATUS = sTAKEBUSINESSSTATUS; }
}